export const GET_DATA_SUCCESS = 'GET_DATA';
export const SORT_DATA = 'SORT_DATA'
export const GET_PRODUCT = 'GET_PRODUCT'
export const EDIT_PRODUCT ='EDIT_PRODUCT'
export const EDIT_DONE = 'EDIT_DONE'
export const DELETE_PRODUCT_SUCCESS = 'DELETE_PRODUCT'
export const USERS_ERROR = 'USERS_ERROR'
export const REQUEST = 'REQUEST';
export const FAILURE = 'FAILURE';
export const DONE = 'DONE';
export const ADD_PRODUCT = 'ADD_PRODUCT'
export const DELETE_ALL_PRODUCT_SUCCESS = 'DELETE_ALL_PRODUCT_SUCCESS'